name: Setup
description: Setup Mise and Gradle

runs:
  using: composite

  steps:
    - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |
          ~/.konan
        key: ${{ runner.os }}-konan-${{ hashFiles('gradle/libs.versions.toml') }}
        restore-keys: ${{ runner.os }}-konan-

    - name: Setup Mise
      uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244 # v4.3.1
